### ISSUE TITLE
使用已有e,n,d重新生成密钥后，无法对字符串进行加密

### ISSUE THREAD

**Issue by Netzhangheng** [shenzheyu/RSA#1]
通过rsa = new RSA(strN, strE, strD); 生成的密钥对，无法对字符串加密，在做*乘法运算return时，无法返回。不太清楚什么情况。

**Comment by Netzhangheng** [comment]
构造函数：BigInt::BigInt(string str, int base) 得到的类，成员变量bool sign没有置为true,导致后面的运算会出现问题。

**Comment by shenzheyu** [comment]
代码有点久远了，感谢关注！
